# Generated by Django 4.2.8 on 2025-11-25 08:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity_utilization', models.IntegerField(default=0, help_text='Capacity utilization percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('plant_capacity', models.IntegerField(default=120, help_text='Total plant capacity')),
                ('trucks_inside', models.IntegerField(default=0, help_text='Number of trucks currently inside')),
                ('capacity_trend_direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=4)),
                ('capacity_trend_percentage', models.FloatField(default=0.0)),
                ('turnaround_avg_day', models.IntegerField(default=0, help_text='Average turnaround time for the day in minutes')),
                ('turnaround_avg_cum', models.IntegerField(default=0, help_text='Cumulative average turnaround time in minutes')),
                ('turnaround_last_year', models.IntegerField(default=0, help_text="Last year's turnaround time in minutes")),
                ('turnaround_trend_direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='down', max_length=4)),
                ('turnaround_trend_percentage', models.FloatField(default=0.0)),
                ('turnaround_performance_color', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue')], default='blue', max_length=10)),
                ('vehicles_in_day', models.IntegerField(default=0)),
                ('vehicles_out_day', models.IntegerField(default=0)),
                ('vehicles_in_cum', models.IntegerField(default=0)),
                ('vehicles_out_cum', models.IntegerField(default=0)),
                ('vehicles_trend_direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=4)),
                ('vehicles_trend_percentage', models.FloatField(default=0.0)),
                ('vehicles_target', models.IntegerField(default=150)),
                ('dispatch_today', models.IntegerField(default=0)),
                ('dispatch_cum_month', models.IntegerField(default=0)),
                ('dispatch_target_day', models.IntegerField(default=120)),
                ('dispatch_trend_direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=4)),
                ('dispatch_trend_percentage', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'KPI Metrics',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TurnaroundTimeSparkline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(help_text='Turnaround time in minutes')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50, unique=True)),
                ('rfid_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tare_weight', models.IntegerField(default=0, help_text='Tare weight in kg')),
                ('weight_after_loading', models.IntegerField(default=0, help_text='Weight after loading in kg')),
                ('progress', models.IntegerField(default=0, help_text='Process progress percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('turnaround_time', models.IntegerField(default=0, help_text='Turnaround time in minutes')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VehicleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_entry_time', models.DateTimeField()),
                ('area', models.CharField(default='AREA-1', max_length=20)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('loading_gate', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ttms.vehicle')),
            ],
            options={
                'ordering': ['-gate_entry_time'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('success', 'Success')], max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='ttms.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('gateEntry', 'Gate Entry'), ('tareWeighing', 'Tare Weighing'), ('loading', 'Loading'), ('postLoadingWeighing', 'Post Loading Weighing'), ('gateExit', 'Gate Exit')], max_length=50)),
                ('state', models.CharField(choices=[('completed', 'Completed'), ('active', 'Active'), ('pending', 'Pending')], max_length=20)),
                ('wait_time', models.IntegerField(default=0, help_text='Wait time in minutes')),
                ('standard_time', models.IntegerField(default=30, help_text='Standard time for this stage in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='ttms.vehicle')),
            ],
            options={
                'ordering': ['vehicle', 'stage'],
                'unique_together': {('vehicle', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='ParkingCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('AREA-1', 'Area 1'), ('AREA-2', 'Area 2')], max_length=10)),
                ('label', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_assignments', to='ttms.vehicle')),
            ],
            options={
                'ordering': ['area', 'label'],
                'unique_together': {('area', 'label')},
            },
        ),
    ]
