# Generated by Django 4.2.8 on 2025-11-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclestage',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclestage',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclestage',
            name='time_taken',
            field=models.IntegerField(default=0, help_text='Actual time taken for this stage in minutes'),
        ),
        migrations.CreateModel(
            name='LoadingGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('area', models.CharField(default='AREA-1', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gate', to='ttms.vehicleentry')),
            ],
            options={
                'ordering': ['area', 'name'],
            },
        ),
    ]
