# Generated by Django 4.2.8 on 2025-11-25 06:30

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTMSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('role', models.CharField(choices=[('operator', 'Operator'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('admin', 'Administrator'), ('viewer', 'Viewer')], default='viewer', help_text='User role in TTMS system', max_length=20)),
                ('facility_id', models.CharField(blank=True, help_text='Associated facility identifier', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='User contact number', max_length=20)),
                ('employee_id', models.CharField(blank=True, help_text='Employee identification number', max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether user can log in')),
                ('last_login_facility', models.CharField(blank=True, help_text='Last facility the user accessed', max_length=100)),
                ('last_login_at', models.DateTimeField(auto_now=True, help_text='Last login timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'TTMS User',
                'verbose_name_plural': 'TTMS Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='ttms_auth_t_email_d8f0ed_idx'), models.Index(fields=['role'], name='ttms_auth_t_role_9a1260_idx'), models.Index(fields=['facility_id'], name='ttms_auth_t_facilit_d58924_idx'), models.Index(fields=['is_active'], name='ttms_auth_t_is_acti_3fc421_idx')],
            },
        ),
    ]
