# Generated by Django 4.2.8 on 2025-11-25 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PTMSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('team_member', 'Team Member'), ('team_lead', 'Team Lead'), ('project_manager', 'Project Manager'), ('admin', 'Administrator'), ('viewer', 'Viewer')], default='viewer', help_text='User role in PTMS system', max_length=20)),
                ('department', models.CharField(blank=True, help_text='User department', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='User contact number', max_length=20)),
                ('employee_id', models.CharField(blank=True, help_text='Employee identification number', max_length=50, null=True, unique=True)),
                ('last_project_id', models.IntegerField(blank=True, help_text='Last project the user accessed', null=True)),
                ('last_login_at', models.DateTimeField(auto_now=True, help_text='Last login timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Link to Django User account', on_delete=django.db.models.deletion.CASCADE, related_name='ptms_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PTMS User Profile',
                'verbose_name_plural': 'PTMS User Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role'], name='ptms_auth_p_role_a4ad80_idx'), models.Index(fields=['department'], name='ptms_auth_p_departm_4714e8_idx'), models.Index(fields=['employee_id'], name='ptms_auth_p_employe_7f8f4c_idx')],
            },
        ),
    ]
